/****************************************************************
 * File: DI8 scan code text labels.h        Created: 2023/07/17 *
 *                                    Last modified: 2023/07/20 *
 *                                                              *
 * Desc:                                                        *
 *                                                              *
 *    Copyright (c) David William Bull. All rights reserved.    *
 ****************************************************************/
#pragma once

#include "typedefs.h"

// Mouse inputs    @ 0x080~0x08B, 0x0A8~0x0AB (16 inputs)
// Joystick inputs @ 0x0B9~0x0C4, 0x0DE~0x0FF (46 inputs)
al32 cchar inputCodeText[256][16] = {
   "<Not bound>",    // 0x000
   "Escape",
   "1",
   "2",
   "3",
   "4",
   "5",
   "6",
   "7",
   "8",
   "9",
   "0",
   "-",
   "=",
   "Backspace",
   "Tab",
   "Q",              // 0x010
   "W",
   "E",
   "R",
   "T",
   "Y",
   "U",
   "I",
   "O",
   "P",
   "[",
   "]",
   "Return",
   "Left Ctrl",
   "A",
   "S",
   "D",              // 0x020
   "F",
   "G",
   "H",
   "J",
   "K",
   "L",
   ";",
   "'",
   "`",
   "Left Shift",
   "\\",
   "Z",
   "X",
   "C",
   "V",
   "B",              // 0x030
   "N",
   "M",
   ",",
   ".",
   "/",
   "Right Shift",
   "*",
   "Left Alt",
   "Spacebar",
   "Capital",
   "F1",
   "F2",
   "F3",
   "F4",
   "F5",
   "F6",             // 0x040
   "F7",
   "F8",
   "F9",
   "F10",
   "Num Lock",
   "Scroll Lock",
   "Numpad 7",
   "Numpad 8",
   "Numpad 9",
   "Numpad -",
   "Numpad 4",
   "Numpad 5",
   "Numpad 6",
   "Numpad +",
   "Numpad 1",
   "Numpad 2",       // 0x050
   "Numpad 3",
   "Numpad 0",
   "Numpad .",
   "0x054",
   "0x055",
   "<> or \\|",
   "F11",
   "F12",
   "0x059",
   "0x05A",
   "0x05B",
   "0x05C",
   "0x05D",
   "0x05E",
   "0x05F",
   "0x060",          // 0x060
   "0x061",
   "0x062",
   "0x063",
   "F13",
   "F14",
   "F15",
   "F16",
   "F17",
   "F18",
   "F19",
   "F20",
   "F21",
   "F22",
   "F23",
   "F24",
   "Kana",           // 0x070
   "0x071",
   "0x072",
   "/",
   "0x074",
   "0x075",
   "0x076",
   "0x077",
   "0x078",
   "Convert",
   "0x07A",
   "No Convert",
   "0x07C",
   "Yen",
   "Numpad .",
   "0x07F",
   "Mouse button 1", // 0x080
   "Mouse button 2",
   "Mouse button 3",
   "Mouse button 4",
   "Mouse button 5",
   "Mouse button 6",
   "Mouse button 7",
   "Mouse button 8",
   "Mouse wheel \24",
   "Mouse wheel \25",
   "Mouse wheel \26",
   "Mouse wheel \27",
   "0x08C",
   "Numpad =",
   "0x08E",
   "0x08F",
   "Previous Track", // 0x090
   "@",
   ":",
   "_",
   "Kanji",
   "Stop",
   "Ax",
   "<No name>",
   "0x098",
   "Next Track",
   "0x09A",
   "0x09B",
   "Numpad Enter",
   "Right Ctrl",
   "0x09E",
   "0x09F",
   "Mute",           // 0x0A0
   "Calculator",
   "Play/Pause",
   "0x0A3",
   "Stop",
   "0x0A5",
   "0x0A6",
   "0x0A7",
   "Mouse \24",
   "Mouse \25",
   "Mouse \27",
   "Mouse \26",
   "0x0AC",
   "0x0AD",
   "Volume Down",
   "0x0AF",
   "Volume Up",      // 0x0B0
   "0x0B1",
   "Web Home",
   "Numpad ,",
   "0x0B4",
   "Numpad /",
   "0x0B6",
   "Print Screen",
   "Right Alt",
   "Pad L \24",
   "Pad L \25",
   "Pad L \26",
   "Pad L \27",
   "Pad R \24",
   "Pad R \25",
   "Pad R \26",
   "Pad R \27",      // 0x0C0
   "Pad POV \24",
   "Pad POV \25",
   "Pad POV \26",
   "Pad POV \27",
   "Pause",
   "0x0C6",
   "Home",
   "\24",
   "Page Up",
   "0x0CA",
   "\27",
   "0x0CC",
   "\26",
   "0x0CE",
   "End",
   "\25",            // 0x0D0
   "Page Down",
   "Insert",
   "Delete",
   "0x0D4",
   "0x0D5",
   "0x0D6",
   "0x0D7",
   "0x0D8",
   "0x0D9",
   "0x0DA",
   "Left Windows",
   "Right Windows",
   "App Menu",
   "Pad L trigger",
   "Pad R trigger",
   "Pad button 1",   // 0x0E0
   "Pad button 2",
   "Pad button 3",
   "Pad button 4",
   "Pad button 5",
   "Pad button 6",
   "Pad button 7",
   "Pad button 8",
   "Pad button 9",
   "Pad button 10",
   "Pad button 11",
   "Pad button 12",
   "Pad button 13",
   "Pad button 14",
   "Pad button 15",
   "Pad button 16",
   "Pad button 17",  // 0x0F0
   "Pad button 18",
   "Pad button 19",
   "Pad button 20",
   "Pad button 21",
   "Pad button 22",
   "Pad button 23",
   "Pad button 24",
   "Pad button 25",
   "Pad button 26",
   "Pad button 27",
   "Pad button 28",
   "Pad button 29",
   "Pad button 30",
   "Pad button 31",
   "Pad button 32"
};
